# ========================================================
# Dreamcoder Dark Night — Dunst theme
# ========================================================
# Include from dunstrc:
#   [include] dreamcoder-dunst.conf

[urgency_low]
    background = "#000000"
    foreground = "#c6c6c6"
    highlight = "#a4afee"
    frame_color = "#5c5c5c"

[urgency_normal]
    background = "#090909"
    foreground = "#c6c6c6"
    highlight = "#a4afee"
    frame_color = "#797979"

[urgency_critical]
    background = "#462828"
    foreground = "#c6c6c6"
    highlight = "#e88484"
    frame_color = "#e88484"
