#!/usr/bin/env bats
# ============================================================================
# gga model pin: scripts/install-gga-pin.sh and scripts/gga-codex-shim.sh.
# Everything runs under the helper's temporary HOME; no real codex is called.
# ============================================================================

load '../helpers/setup'
bats_require_minimum_version 1.5.0

installer() { "${DREAMCODER_DOTS_DIR}/scripts/install-gga-pin.sh" "$@"; }

gga_setup() {
    unset XDG_CONFIG_HOME GGA_PROVIDER
    GGA_DIR="${HOME}/.config/gga"
    SHIM_DIR="${GGA_DIR}/bin"
    CONFIG="${GGA_DIR}/config"
    PIN="${GGA_DIR}/pin.env"
    ENV_D="${HOME}/.config/environment.d/50-gga-pin.conf"
    # Fake codex that prints its argv, one argument per line.
    REAL_BIN="${HOME}/real-bin"
    mkdir -p "${REAL_BIN}" "${HOME}/fake-gga"
    printf '#!/usr/bin/env bash\nprintf "%%s\\n" "$@"\n' >"${REAL_BIN}/codex"
    # Fake gga that calls codex as a child process, like gga's execute_codex.
    printf '#!/usr/bin/env bash\ncodex "$@"\n' >"${HOME}/fake-gga/gga"
    chmod +x "${REAL_BIN}/codex" "${HOME}/fake-gga/gga"
}

gentle_ai_config() {
    mkdir -p "${GGA_DIR}"
    printf '%s\n' '# Gentleman Guardian Angel Configuration' '# Generated by gentle-ai' '' \
        'PROVIDER="claude"' '' 'RULES_FILE="AGENTS.md"' >"${CONFIG}"
}

snapshot() { find "${HOME}/.config" -type f -exec sha256sum {} + 2>/dev/null | sort; }

# Run the installed shim with the fake codex behind it.
shim() { PATH="${SHIM_DIR}:${REAL_BIN}:${PATH}" "$@"; }

# ── installer ────────────────────────────────────────────────────────

@test "installer creates shim, pin.env, config block and environment.d file" {
    gga_setup
    run installer
    [ "$status" -eq 0 ]
    [ -x "${SHIM_DIR}/codex" ]
    cmp -s "${SHIM_DIR}/codex" "${DREAMCODER_DOTS_DIR}/scripts/gga-codex-shim.sh"
    grep -qx 'GGA_PIN_MODEL="gpt-6.1-sol"' "${PIN}"
    grep -qx 'GGA_PIN_EFFORT="medium"' "${PIN}"
    grep -qx '# >>> dreamcoder gga pin >>>' "${CONFIG}"
    grep -qx 'GGA_PROVIDER=codex' "${ENV_D}"
    grep -qx "PATH=${SHIM_DIR}:\${PATH}" "${ENV_D}"
    [ "$(grep -c '^✓' <<<"$output")" -eq 4 ]
}

@test "installer is idempotent: second run prints nothing and changes nothing" {
    gga_setup
    gentle_ai_config
    installer >/dev/null
    before="$(snapshot)"
    run installer
    [ "$status" -eq 0 ]
    [ -z "$output" ]
    [ "$(snapshot)" = "${before}" ]
}

@test "installer replaces an existing block instead of duplicating it" {
    gga_setup
    gentle_ai_config
    printf '\n%s\n%s\n%s\n' '# >>> dreamcoder gga pin >>>' 'PROVIDER="stale"' '# <<< dreamcoder gga pin <<<' >>"${CONFIG}"
    printf 'TIMEOUT="300"\n' >>"${CONFIG}"
    installer >/dev/null
    [ "$(grep -c '^# >>> dreamcoder gga pin >>>$' "${CONFIG}")" -eq 1 ]
    run grep -q 'stale' "${CONFIG}"
    [ "$status" -ne 0 ]
    # The block moves to the end and the user's lines survive.
    [ "$(tail -n1 "${CONFIG}")" = '# <<< dreamcoder gga pin <<<' ]
    grep -qx 'TIMEOUT="300"' "${CONFIG}"
}

@test "a gentle-ai rewritten config gets the block and resolves to codex" {
    gga_setup
    gentle_ai_config
    installer >/dev/null
    head -n2 "${CONFIG}" | grep -qx '# Generated by gentle-ai'
    grep -qx 'RULES_FILE="AGENTS.md"' "${CONFIG}"
    run env -u GGA_PROVIDER bash -c 'source "$1"; printf "%s %s %s\n" "$PROVIDER" "$GGA_PROVIDER" "${PATH%%:*}"' _ "${CONFIG}"
    [ "$status" -eq 0 ]
    [ "$output" = "codex codex ${SHIM_DIR}" ]
}

@test "sourcing the block twice does not duplicate the shim dir on PATH" {
    gga_setup
    installer >/dev/null
    run bash -c 'source "$1"; source "$1"; tr ":" "\n" <<<"$PATH" | grep -cx "$2"' _ "${CONFIG}" "${SHIM_DIR}"
    [ "$output" = "1" ]
}

@test "installer never overwrites a user-edited pin.env" {
    gga_setup
    mkdir -p "${GGA_DIR}"
    printf 'GGA_PIN_MODEL="custom-model"\n' >"${PIN}"
    installer >/dev/null
    [ "$(cat "${PIN}")" = 'GGA_PIN_MODEL="custom-model"' ]
}

@test "installer --dry-run writes nothing" {
    gga_setup
    gentle_ai_config
    before="$(snapshot)"
    run installer --dry-run
    [ "$status" -eq 0 ]
    [[ "$output" == *"Would update"* ]]
    [ "$(snapshot)" = "${before}" ]
    [ ! -e "${SHIM_DIR}/codex" ]
}

@test "installer refuses an unterminated pin block" {
    gga_setup
    gentle_ai_config
    printf '# >>> dreamcoder gga pin >>>\n' >>"${CONFIG}"
    run installer
    [ "$status" -ne 0 ]
    grep -qx 'PROVIDER="claude"' "${CONFIG}"
}

@test "installer refuses a config dir that is unsafe to embed in shell code" {
    gga_setup
    export XDG_CONFIG_HOME="${HOME}/cfg\$(touch pwned)"
    run installer
    [ "$status" -ne 0 ]
    [[ "$output" == *"unsupported characters"* ]]
    [ ! -e "${XDG_CONFIG_HOME}" ]
}

# ── shim ─────────────────────────────────────────────────────────────

@test "shim injects the pinned model when gga runs codex exec" {
    gga_setup
    installer >/dev/null
    run shim "${HOME}/fake-gga/gga" exec "review this"
    [ "$status" -eq 0 ]
    [ "$output" = "$(printf '%s\n' exec -m gpt-6.1-sol -c model_reasoning_effort=medium 'review this')" ]
}

@test "shim also detects gga through an intermediate process" {
    gga_setup
    installer >/dev/null
    printf '#!/usr/bin/env bash\nbash -c '\''codex "$@"'\'' _ "$@"\n' >"${HOME}/fake-gga/gga"
    run shim "${HOME}/fake-gga/gga" exec "review this"
    [ "${lines[1]}" = "-m" ]
    [ "${lines[2]}" = "gpt-6.1-sol" ]
}

@test "shim passes codex exec through untouched without a gga ancestor" {
    gga_setup
    installer >/dev/null
    run shim bash -c 'codex exec "hello"'
    [ "$status" -eq 0 ]
    [ "$output" = "$(printf '%s\n' exec hello)" ]
}

@test "shim keeps an explicit model from the caller" {
    gga_setup
    installer >/dev/null
    run shim "${HOME}/fake-gga/gga" exec -m other-model "review"
    [ "$output" = "$(printf '%s\n' exec -m other-model review)" ]
    run shim "${HOME}/fake-gga/gga" exec --model=other-model "review"
    [ "$output" = "$(printf '%s\n' exec --model=other-model review)" ]
}

@test "shim leaves non-exec subcommands untouched under gga" {
    gga_setup
    installer >/dev/null
    run shim "${HOME}/fake-gga/gga" login --status
    [ "$output" = "$(printf '%s\n' login --status)" ]
}

@test "pin.env overrides model and effort" {
    gga_setup
    installer >/dev/null
    printf 'GGA_PIN_MODEL="gpt-x"\nexport GGA_PIN_EFFORT=high\n' >"${PIN}"
    run shim "${HOME}/fake-gga/gga" exec "review"
    [ "$output" = "$(printf '%s\n' exec -m gpt-x -c model_reasoning_effort=high review)" ]
}

@test "shim fails clearly when no real codex exists" {
    gga_setup
    installer >/dev/null
    run -127 env PATH="${SHIM_DIR}:/usr/bin:/bin" codex exec x
    [[ "$output" == *"real codex CLI was not found"* ]]
}
