"""Focused extra Dreamcoder theme renderers."""

from __future__ import annotations

from typing import Any

from .renderers_extra_nvim_lsp import nvim_lsp_groups
from .renderers_extra_nvim_plugins import nvim_plugin_groups
from .renderers_extra_nvim_syntax import nvim_syntax_groups
from .renderers_extra_nvim_ui import nvim_ui_groups


def nvim_dispatcher_content() -> str:
    """Return a dispatcher that loads the correct variant.

    Priority:
      1. DREAMCODER_THEME_MODE env var (set by `dreamcoder dark` / `dreamcoder light`)
      2. ~/.cache/dreamcoder/cursor-cli.env (written by apply-theme-mode.sh)
      3. vim.o.background (Neovim's own mode)
      4. Fallback: "dark"
    """
    return """-- ========================================================
-- Dreamcoder — auto-detect dispatcher
-- ========================================================
-- Usage: vim.cmd.colorscheme("dreamcoder")
-- Auto-loads the correct variant based on:
--   1. DREAMCODER_THEME_MODE env var (set by `dreamcoder light`)
--   2. ~/.cache/dreamcoder/cursor-cli.env (persisted by apply-theme-mode.sh)
--   3. vim.o.background (Neovim's own setting)
--   4. Fallback: dark
-- Direct variant access: colorscheme dreamcoder-dark / dreamcoder-light
-- ========================================================

vim.g.colors_name = "dreamcoder"

-- Glass blur stays dark-only; light needs opaque paper backgrounds for readability.
vim.opt.winblend = 10
vim.opt.pumblend = 10

-- Find variant files relative to this file's location
local src = debug.getinfo(1, "S").source:match("@?(.*)")
local theme_dir = src:match("^(.*[/\\\\])") or "."

-- Resolve base mode: env var > cache file > vim.o.background > dark
local mode = vim.env.DREAMCODER_THEME_MODE

if not mode then
  local cache_file = vim.fn.expand("~/.cache/dreamcoder/cursor-cli.env")
  local f = io.open(cache_file, "r")
  if f then
    for line in f:lines() do
      local m = line:match('^export DREAMCODER_THEME_MODE="(.-)"')
      if m then
        mode = m
        break
      end
    end
    f:close()
  end
end

if not mode then
  mode = vim.o.background or "dark"
end

if mode == "dark" then
  dofile(theme_dir .. "dreamcoder-dark.lua")
else
  dofile(theme_dir .. "dreamcoder-light.lua")
end
"""


def nvim_content(c: dict[str, str]) -> str:
    """Return a Neovim Lua colorscheme using the Dreamcoder palette."""

    def hl(name: str, **kwargs: Any) -> str:
        parts = []
        if "fg" in kwargs:
            parts.append(f'    fg = "{kwargs["fg"]}"')
        if "bg" in kwargs:
            parts.append(f'    bg = "{kwargs["bg"]}"')
        if "sp" in kwargs:
            parts.append(f'    sp = "{kwargs["sp"]}"')
        if kwargs.get("bold"):
            parts.append("    bold = true")
        if kwargs.get("italic"):
            parts.append("    italic = true")
        if kwargs.get("underline"):
            parts.append("    underline = true")
        if kwargs.get("undercurl"):
            parts.append("    undercurl = true")
        if kwargs.get("strikethrough"):
            parts.append("    strikethrough = true")
        if kwargs.get("reverse"):
            parts.append("    reverse = true")
        inner = ",\n".join(parts)
        return f'  vim.api.nvim_set_hl(0, "{name}", {{\n{inner}\n  }})\n'

    invert = c["details"] == "lighter"
    variant_name = "light" if invert else "dark"
    bg = c["bg"]
    normal_bg = bg if invert else "none"
    text = c["text"]
    fg = text
    sel_bg = c["selection_bg"]
    sel_fg = c["selection_fg"]

    lines = [
        f"""-- ========================================================
-- {c["name"]} — generated by Dreamcoder sync
-- ========================================================
-- Loaded by the dreamcoder dispatcher (colors/dreamcoder.lua).
-- Can also be loaded directly: vim.cmd.colorscheme("dreamcoder-{variant_name}")
-- ========================================================

vim.g.colors_name = "dreamcoder-{variant_name}"

local c = {{
  bg        = "{bg}",
  surface0  = "{c["surface0"]}",
  surface1  = "{c["surface1"]}",
  surface2  = "{c["surface2"]}",
  text      = "{text}",
  muted     = "{c["muted"]}",
  subtle    = "{c["subtle"]}",
  comment   = "{c["comment"]}",
  accent    = "{c["accent"]}",
  accent2   = "{c["accent_2"]}",
  diagnostic = "{c["diagnostic"]}",
  sage      = "{c["sage"]}",
  lavender  = "{c["lavender"]}",
  mauve     = "{c["mauve"]}",
  error     = "{c["error"]}",
  warning   = "{c["warning"]}",
  border    = "{c["border"]}",
  border_ui = "{c["border_ui"]}",
  selection = "{sel_bg}",
}}

local function h(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- ── Editor UI ────────────────────────────────────────────────
-- Normal background is opaque in light so dark terminal transparency cannot hide text.
-- Dreamcoder Dark keeps transparent Normal for the glass effect.
""",
    ]
    group_args = (hl, c, fg, bg, sel_fg, sel_bg)
    lines.extend(nvim_ui_groups(hl, c, fg, bg, sel_fg, sel_bg, normal_bg))
    lines.extend(nvim_syntax_groups(*group_args))
    lines.extend(nvim_lsp_groups(*group_args))
    lines.extend(nvim_plugin_groups(*group_args))

    return "\n".join(lines)


from .renderer_adapters import NvimDispatcherAdapter  # noqa: E402
from .renderer_contract import (  # noqa: E402
    ActiveStrategy,
    MutationStrategy,
    RendererRegistration,
    RendererStrategy,
    RepositoryStrategy,
    SyncDefinition,
)

REGISTRATIONS: tuple[RendererRegistration, ...] = (
    RendererRegistration(
        consumer_id="nvim",
        renderer=NvimDispatcherAdapter(),
        contract_version=1,
        modes=frozenset({"dark", "light"}),
        output_kind="active-and-repository",
        sync=SyncDefinition(
            renderer=RendererStrategy.NVIM_DISPATCHER,
            active=ActiveStrategy.RESOLVED_ACTIVE_PATH,
            repository=RepositoryStrategy.MODE_VARIANTS,
            mutation=MutationStrategy.WRITE_IF_CHANGED,
        ),
        summary_label="Neovim dispatcher + variants",
    ),
)
