#!/usr/bin/env bash
# ============================================================================
# ml4w.sh — ML4W ownership predicates (pure; no side effects)
# ============================================================================
# This library deliberately omits `set -euo pipefail`: sourcing a library must
# not mutate the caller's shell options. Callers set their own options before
# sourcing this file.
#
# ML4W ownership is accepted from either supported layout:
#   - old layout: individual config files symlinked from the ML4W dotfiles
#   - current layout: ~/.config/<app> is a real directory (or a symlink) backed
#     by the ML4W dotfiles repo and carrying ML4W-specific marker files
# ============================================================================

hyprland_is_ml4w_managed() {
    [[ -L "${HOME}/.config/hypr/hyprland.conf" ]] && return 0
    [[ -L "${HOME}/.config/hypr" ]] && return 0
    [[ -f "${HOME}/.config/hypr/conf/keybinding.lua" ]] && return 0
    return 1
}

waybar_is_ml4w_managed() {
    [[ -L "${HOME}/.config/waybar/config.jsonc" ]] && return 0
    [[ -L "${HOME}/.config/waybar" ]] && return 0
    [[ -f "${HOME}/.config/waybar/launch.sh" ]] && return 0
    return 1
}

# A config path is ML4W-managed when it is a symlink itself, or when it resolves
# into the ML4W dotfiles root. ML4W 2.16 links whole app directories
# (~/.config/rofi -> ~/.mydotfiles/...), so the files inside are regular files from
# the link's point of view while ML4W still owns them. ML4W_DOTFILES_DIR relocates
# the root for non-default installs.
path_is_ml4w_managed() {
    local path="$1" real root="${ML4W_DOTFILES_DIR:-${HOME}/.mydotfiles}"
    [[ -e "${path}" ]] || return 1
    [[ -L "${path}" ]] && return 0
    real="$(readlink -f -- "${path}")" || return 1
    [[ "${real}" == "${root}/"* ]]
}

# Hyprland colour files (colors.lua / colors.conf) carry Dreamcoder colours when
# they are a symlink into a Dreamcoder variant, or a regular file byte-identical
# to one of the DreamcoderThemes hypr-colors-* variants. Regular files are the
# supported layout: ML4W 2.16 ships them as regular files and the theme sync
# writes through whatever sits at the path (it only flips existing symlinks).
# True when the path is a symlink whose target name carries "dreamcoder".
_is_dreamcoder_symlink() {
    [[ -L "$1" && "$(readlink "$1")" == *dreamcoder* ]]
}

hypr_colors_is_dreamcoder() {
    local path="$1" variant
    [[ -e "${path}" ]] || return 1
    _is_dreamcoder_symlink "${path}" && return 0
    for variant in "${DREAMCODER_DOTS_DIR}"/DreamcoderThemes/dreamcoder/hypr-colors-*."${path##*.}"; do
        [[ -f "${variant}" ]] && cmp -s "${path}" "${variant}" && return 0
    done
    return 1
}

# Waybar colors.css carries Dreamcoder colours when it is a symlink into a
# Dreamcoder variant, or a regular file written by the theme sync (identified by
# its generator header). The sync renders the active mode straight into the
# path, so a regular file is the supported layout on ML4W 2.16.
waybar_colors_is_dreamcoder() {
    local path="$1"
    [[ -e "${path}" ]] || return 1
    _is_dreamcoder_symlink "${path}" && return 0
    [[ -L "${path}" ]] && return 1
    head -n 5 "${path}" | grep -q 'Generated by Dreamcoder sync'
}
