# ========================================================
# Dreamcoder Dark — Dunst theme
# ========================================================
# Include from dunstrc:
#   [include] dreamcoder-dunst.conf

[urgency_low]
    background = "#000000"
    foreground = "#E6E6E6"
    highlight = "#A5B4FC"
    frame_color = "#6B6B6B"

[urgency_normal]
    background = "#0B0B0B"
    foreground = "#E6E6E6"
    highlight = "#A5B4FC"
    frame_color = "#767676"

[urgency_critical]
    background = "#4b2828"
    foreground = "#E6E6E6"
    highlight = "#FB8585"
    frame_color = "#FB8585"
