# Dreamcoder Dark Night — Lazygit theme
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  theme:
    activeBorderColor:
      - "#a4afee" # accent
      - "bold"
    inactiveBorderColor:
      - "#5c5c5c" # border
    searchingActiveBorderColor:
      - "#b48ce9" # accent-2
      - "bold"
    optionsTextColor:
      - "#62b9e2" # diagnostic
    selectedLineBgColor:
      - "#323232" # selection
    inactiveViewSelectedLineBgColor:
      - "#1b1b1b" # surface-2
    cherryPickedCommitFgColor:
      - "#62b9e2"
    cherryPickedCommitBgColor:
      - "#b48ce9"
    markedBaseCommitFgColor:
      - "#62b9e2"
    markedBaseCommitBgColor:
      - "#a4afee"
    unstagedChangesColor:
      - "#e88484" # error
    defaultFgColor:
      - "#c6c6c6" # text
  authorColors:
        "#a4afee": "#000000"
        "#b48ce9": "#000000"
        "#62b9e2": "#000000"
        "#43b48b": "#000000"
        "#b98beb": "#000000"
  showFileTree: true
  showRandomTip: false
  nerdFontsVersion: "3"
  sidePanelWidth: 0.3
  expandFocusedSidePanel: true
  mainPanelSplitMode: "flexible"
  language: "en"
git:
  diffRenderers:
    - colorArg: always
      command: delta --syntax-theme "Catppuccin Mocha" --paging=never
  merging:
    manualCommit: false
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --graph --pretty=format:'%C(#a4afee)%h%Creset -%C(#b48ce9)%d%Creset %s %C(#b3b3b3)(%cr) %C(#62b9e2)<%an>%Creset' --date=relative"
update:
  method: never
