# Dreamcoder Light — Lazygit theme
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  theme:
    activeBorderColor:
      - "#824f16" # accent
      - "bold"
    inactiveBorderColor:
      - "#8a7358" # border
    searchingActiveBorderColor:
      - "#a7471c" # accent-2
      - "bold"
    optionsTextColor:
      - "#0d4a68" # diagnostic
    selectedLineBgColor:
      - "#decbb1" # selection
    inactiveViewSelectedLineBgColor:
      - "#c8ad89" # surface-2
    cherryPickedCommitFgColor:
      - "#0d4a68"
    cherryPickedCommitBgColor:
      - "#a7471c"
    markedBaseCommitFgColor:
      - "#0d4a68"
    markedBaseCommitBgColor:
      - "#824f16"
    unstagedChangesColor:
      - "#842f24" # error
    defaultFgColor:
      - "#17120d" # text
  authorColors:
        "#824f16": "#f3eadc"
        "#a7471c": "#f3eadc"
        "#0d4a68": "#f3eadc"
        "#315b31": "#f3eadc"
        "#57478b": "#f3eadc"
        "#7d3e64": "#f3eadc"
  showFileTree: true
  showRandomTip: false
  nerdFontsVersion: "3"
  sidePanelWidth: 0.3
  expandFocusedSidePanel: true
  mainPanelSplitMode: "flexible"
  language: "en"
git:
  diffRenderers:
    - colorArg: always
      command: delta --syntax-theme "Catppuccin Latte" --paging=never
  merging:
    manualCommit: false
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --graph --pretty=format:'%C(#824f16)%h%Creset -%C(#a7471c)%d%Creset %s %C(#725e4c)(%cr) %C(#0d4a68)<%an>%Creset' --date=relative"
update:
  method: never
